version: 2
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux    
    ldflags:
      - -s -w -X github.com/mpapenbr/iracelog-graphql/graph.Version={{.Version}}

dockers:
  - id: graphql-amd64
    image_templates:
      - "ghcr.io/mpapenbr/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://{{.ModulePath}}"
      - "--label=org.opencontainers.image.url=https://{{.ModulePath}}"
      - "--label=org.opencontainers.image.description=GraphQL for iRacelog"
      - "--label=org.opencontainers.image.licenses=MIT license"
      - "--build-arg=ARCH=amd64"
      - "--platform=linux/amd64"
    extra_files:
      - ext/healthcheck/grpc_health_probe.amd64
    use: buildx
    goarch: amd64

  - id: graphql-arm64
    image_templates:
      - "ghcr.io/mpapenbr/{{ .ProjectName }}:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://{{.ModulePath}}"
      - "--label=org.opencontainers.image.url=https://{{.ModulePath}}"
      - "--label=org.opencontainers.image.description=GraphQL for iRacelog"
      - "--label=org.opencontainers.image.licenses=MIT license"
      - "--build-arg=ARCH=arm64"
      - "--platform=linux/arm64"
    extra_files:
      - ext/healthcheck/grpc_health_probe.arm64
    use: buildx
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/mpapenbr/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/mpapenbr/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/mpapenbr/{{ .ProjectName }}:{{ .Tag }}-arm64"


snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*!?:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*!?:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

release:
  footer: |
    ---
    _Released with [GoReleaser](https://goreleaser.com)!_
