// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// CCarEntry is an object representing the database table.
type CCarEntry struct {
	ID           int32  `db:"id,pk" `
	EventID      int32  `db:"event_id" `
	CCarID       int32  `db:"c_car_id" `
	CarIdx       int32  `db:"car_idx" `
	CarNumber    string `db:"car_number" `
	CarNumberRaw int32  `db:"car_number_raw" `

	R cCarEntryR `db:"-" `
}

// CCarEntrySlice is an alias for a slice of pointers to CCarEntry.
// This should almost always be used instead of []*CCarEntry.
type CCarEntrySlice []*CCarEntry

// CCarEntries contains methods to work with the c_car_entry table
var CCarEntries = psql.NewTablex[*CCarEntry, CCarEntrySlice, *CCarEntrySetter]("", "c_car_entry")

// CCarEntriesQuery is a query on the c_car_entry table
type CCarEntriesQuery = *psql.ViewQuery[*CCarEntry, CCarEntrySlice]

// cCarEntryR is where relationships are stored.
type cCarEntryR struct {
	CCarDrivers CCarDriverSlice // c_car_driver.c_car_driver_car_entry_id_fkey
	CCar        *CCar           // c_car_entry.c_car_entry_car_id_fkey
	Event       *Event          // c_car_entry.c_car_entry_event_id_fkey
	CCarTeams   CCarTeamSlice   // c_car_team.c_car_team_car_entry_id_fkey
}

type cCarEntryColumnNames struct {
	ID           string
	EventID      string
	CCarID       string
	CarIdx       string
	CarNumber    string
	CarNumberRaw string
}

var CCarEntryColumns = buildCCarEntryColumns("c_car_entry")

type cCarEntryColumns struct {
	tableAlias   string
	ID           psql.Expression
	EventID      psql.Expression
	CCarID       psql.Expression
	CarIdx       psql.Expression
	CarNumber    psql.Expression
	CarNumberRaw psql.Expression
}

func (c cCarEntryColumns) Alias() string {
	return c.tableAlias
}

func (cCarEntryColumns) AliasedAs(alias string) cCarEntryColumns {
	return buildCCarEntryColumns(alias)
}

func buildCCarEntryColumns(alias string) cCarEntryColumns {
	return cCarEntryColumns{
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		EventID:      psql.Quote(alias, "event_id"),
		CCarID:       psql.Quote(alias, "c_car_id"),
		CarIdx:       psql.Quote(alias, "car_idx"),
		CarNumber:    psql.Quote(alias, "car_number"),
		CarNumberRaw: psql.Quote(alias, "car_number_raw"),
	}
}

type cCarEntryWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, int32]
	EventID      psql.WhereMod[Q, int32]
	CCarID       psql.WhereMod[Q, int32]
	CarIdx       psql.WhereMod[Q, int32]
	CarNumber    psql.WhereMod[Q, string]
	CarNumberRaw psql.WhereMod[Q, int32]
}

func (cCarEntryWhere[Q]) AliasedAs(alias string) cCarEntryWhere[Q] {
	return buildCCarEntryWhere[Q](buildCCarEntryColumns(alias))
}

func buildCCarEntryWhere[Q psql.Filterable](cols cCarEntryColumns) cCarEntryWhere[Q] {
	return cCarEntryWhere[Q]{
		ID:           psql.Where[Q, int32](cols.ID),
		EventID:      psql.Where[Q, int32](cols.EventID),
		CCarID:       psql.Where[Q, int32](cols.CCarID),
		CarIdx:       psql.Where[Q, int32](cols.CarIdx),
		CarNumber:    psql.Where[Q, string](cols.CarNumber),
		CarNumberRaw: psql.Where[Q, int32](cols.CarNumberRaw),
	}
}

// CCarEntrySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CCarEntrySetter struct {
	ID           omit.Val[int32]  `db:"id,pk" `
	EventID      omit.Val[int32]  `db:"event_id" `
	CCarID       omit.Val[int32]  `db:"c_car_id" `
	CarIdx       omit.Val[int32]  `db:"car_idx" `
	CarNumber    omit.Val[string] `db:"car_number" `
	CarNumberRaw omit.Val[int32]  `db:"car_number_raw" `
}

func (s CCarEntrySetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.EventID.IsUnset() {
		vals = append(vals, "event_id")
	}

	if !s.CCarID.IsUnset() {
		vals = append(vals, "c_car_id")
	}

	if !s.CarIdx.IsUnset() {
		vals = append(vals, "car_idx")
	}

	if !s.CarNumber.IsUnset() {
		vals = append(vals, "car_number")
	}

	if !s.CarNumberRaw.IsUnset() {
		vals = append(vals, "car_number_raw")
	}

	return vals
}

func (s CCarEntrySetter) Overwrite(t *CCarEntry) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.EventID.IsUnset() {
		t.EventID, _ = s.EventID.Get()
	}
	if !s.CCarID.IsUnset() {
		t.CCarID, _ = s.CCarID.Get()
	}
	if !s.CarIdx.IsUnset() {
		t.CarIdx, _ = s.CarIdx.Get()
	}
	if !s.CarNumber.IsUnset() {
		t.CarNumber, _ = s.CarNumber.Get()
	}
	if !s.CarNumberRaw.IsUnset() {
		t.CarNumberRaw, _ = s.CarNumberRaw.Get()
	}
}

func (s *CCarEntrySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return CCarEntries.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsUnset() {
			vals[0] = psql.Raw("DEFAULT")
		} else {
			vals[0] = psql.Arg(s.ID)
		}

		if s.EventID.IsUnset() {
			vals[1] = psql.Raw("DEFAULT")
		} else {
			vals[1] = psql.Arg(s.EventID)
		}

		if s.CCarID.IsUnset() {
			vals[2] = psql.Raw("DEFAULT")
		} else {
			vals[2] = psql.Arg(s.CCarID)
		}

		if s.CarIdx.IsUnset() {
			vals[3] = psql.Raw("DEFAULT")
		} else {
			vals[3] = psql.Arg(s.CarIdx)
		}

		if s.CarNumber.IsUnset() {
			vals[4] = psql.Raw("DEFAULT")
		} else {
			vals[4] = psql.Arg(s.CarNumber)
		}

		if s.CarNumberRaw.IsUnset() {
			vals[5] = psql.Raw("DEFAULT")
		} else {
			vals[5] = psql.Arg(s.CarNumberRaw)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CCarEntrySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CCarEntrySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.EventID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "event_id")...),
			psql.Arg(s.EventID),
		}})
	}

	if !s.CCarID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "c_car_id")...),
			psql.Arg(s.CCarID),
		}})
	}

	if !s.CarIdx.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "car_idx")...),
			psql.Arg(s.CarIdx),
		}})
	}

	if !s.CarNumber.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "car_number")...),
			psql.Arg(s.CarNumber),
		}})
	}

	if !s.CarNumberRaw.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "car_number_raw")...),
			psql.Arg(s.CarNumberRaw),
		}})
	}

	return exprs
}

// FindCCarEntry retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCCarEntry(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*CCarEntry, error) {
	if len(cols) == 0 {
		return CCarEntries.Query(
			SelectWhere.CCarEntries.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return CCarEntries.Query(
		SelectWhere.CCarEntries.ID.EQ(IDPK),
		sm.Columns(CCarEntries.Columns().Only(cols...)),
	).One(ctx, exec)
}

// CCarEntryExists checks the presence of a single record by primary key
func CCarEntryExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return CCarEntries.Query(
		SelectWhere.CCarEntries.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after CCarEntry is retrieved from the database
func (o *CCarEntry) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CCarEntries.AfterSelectHooks.RunHooks(ctx, exec, CCarEntrySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = CCarEntries.AfterInsertHooks.RunHooks(ctx, exec, CCarEntrySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = CCarEntries.AfterUpdateHooks.RunHooks(ctx, exec, CCarEntrySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = CCarEntries.AfterDeleteHooks.RunHooks(ctx, exec, CCarEntrySlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the CCarEntry
func (o *CCarEntry) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *CCarEntry) pkEQ() dialect.Expression {
	return psql.Quote("c_car_entry", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the CCarEntry
func (o *CCarEntry) Update(ctx context.Context, exec bob.Executor, s *CCarEntrySetter) error {
	v, err := CCarEntries.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single CCarEntry record with an executor
func (o *CCarEntry) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := CCarEntries.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the CCarEntry using the executor
func (o *CCarEntry) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := CCarEntries.Query(
		SelectWhere.CCarEntries.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CCarEntrySlice is retrieved from the database
func (o CCarEntrySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CCarEntries.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = CCarEntries.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = CCarEntries.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = CCarEntries.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CCarEntrySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("c_car_entry", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CCarEntrySlice) copyMatchingRows(from ...*CCarEntry) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CCarEntrySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CCarEntries.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CCarEntry:
				o.copyMatchingRows(retrieved)
			case []*CCarEntry:
				o.copyMatchingRows(retrieved...)
			case CCarEntrySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CCarEntry or a slice of CCarEntry
				// then run the AfterUpdateHooks on the slice
				_, err = CCarEntries.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CCarEntrySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CCarEntries.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CCarEntry:
				o.copyMatchingRows(retrieved)
			case []*CCarEntry:
				o.copyMatchingRows(retrieved...)
			case CCarEntrySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CCarEntry or a slice of CCarEntry
				// then run the AfterDeleteHooks on the slice
				_, err = CCarEntries.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CCarEntrySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CCarEntrySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CCarEntries.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CCarEntrySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CCarEntries.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CCarEntrySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := CCarEntries.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type cCarEntryJoins[Q dialect.Joinable] struct {
	typ         string
	CCarDrivers func(context.Context) modAs[Q, cCarDriverColumns]
	CCar        func(context.Context) modAs[Q, cCarColumns]
	Event       func(context.Context) modAs[Q, eventColumns]
	CCarTeams   func(context.Context) modAs[Q, cCarTeamColumns]
}

func (j cCarEntryJoins[Q]) aliasedAs(alias string) cCarEntryJoins[Q] {
	return buildCCarEntryJoins[Q](buildCCarEntryColumns(alias), j.typ)
}

func buildCCarEntryJoins[Q dialect.Joinable](cols cCarEntryColumns, typ string) cCarEntryJoins[Q] {
	return cCarEntryJoins[Q]{
		typ:         typ,
		CCarDrivers: cCarEntriesJoinCCarDrivers[Q](cols, typ),
		CCar:        cCarEntriesJoinCCar[Q](cols, typ),
		Event:       cCarEntriesJoinEvent[Q](cols, typ),
		CCarTeams:   cCarEntriesJoinCCarTeams[Q](cols, typ),
	}
}

func cCarEntriesJoinCCarDrivers[Q dialect.Joinable](from cCarEntryColumns, typ string) func(context.Context) modAs[Q, cCarDriverColumns] {
	return func(ctx context.Context) modAs[Q, cCarDriverColumns] {
		return modAs[Q, cCarDriverColumns]{
			c: CCarDriverColumns,
			f: func(to cCarDriverColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CCarDrivers.Name().As(to.Alias())).On(
						to.CCarEntryID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

func cCarEntriesJoinCCar[Q dialect.Joinable](from cCarEntryColumns, typ string) func(context.Context) modAs[Q, cCarColumns] {
	return func(ctx context.Context) modAs[Q, cCarColumns] {
		return modAs[Q, cCarColumns]{
			c: CCarColumns,
			f: func(to cCarColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CCars.Name().As(to.Alias())).On(
						to.ID.EQ(from.CCarID),
					))
				}

				return mods
			},
		}
	}
}

func cCarEntriesJoinEvent[Q dialect.Joinable](from cCarEntryColumns, typ string) func(context.Context) modAs[Q, eventColumns] {
	return func(ctx context.Context) modAs[Q, eventColumns] {
		return modAs[Q, eventColumns]{
			c: EventColumns,
			f: func(to eventColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Events.Name().As(to.Alias())).On(
						to.ID.EQ(from.EventID),
					))
				}

				return mods
			},
		}
	}
}

func cCarEntriesJoinCCarTeams[Q dialect.Joinable](from cCarEntryColumns, typ string) func(context.Context) modAs[Q, cCarTeamColumns] {
	return func(ctx context.Context) modAs[Q, cCarTeamColumns] {
		return modAs[Q, cCarTeamColumns]{
			c: CCarTeamColumns,
			f: func(to cCarTeamColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CCarTeams.Name().As(to.Alias())).On(
						to.CCarEntryID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

// CCarDrivers starts a query for related objects on c_car_driver
func (o *CCarEntry) CCarDrivers(mods ...bob.Mod[*dialect.SelectQuery]) CCarDriversQuery {
	return CCarDrivers.Query(append(mods,
		sm.Where(CCarDriverColumns.CCarEntryID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CCarEntrySlice) CCarDrivers(mods ...bob.Mod[*dialect.SelectQuery]) CCarDriversQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ID)
	}

	return CCarDrivers.Query(append(mods,
		sm.Where(psql.Group(CCarDriverColumns.CCarEntryID).In(PKArgs...)),
	)...)
}

// CCar starts a query for related objects on c_car
func (o *CCarEntry) CCar(mods ...bob.Mod[*dialect.SelectQuery]) CCarsQuery {
	return CCars.Query(append(mods,
		sm.Where(CCarColumns.ID.EQ(psql.Arg(o.CCarID))),
	)...)
}

func (os CCarEntrySlice) CCar(mods ...bob.Mod[*dialect.SelectQuery]) CCarsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.CCarID)
	}

	return CCars.Query(append(mods,
		sm.Where(psql.Group(CCarColumns.ID).In(PKArgs...)),
	)...)
}

// Event starts a query for related objects on event
func (o *CCarEntry) Event(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	return Events.Query(append(mods,
		sm.Where(EventColumns.ID.EQ(psql.Arg(o.EventID))),
	)...)
}

func (os CCarEntrySlice) Event(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.EventID)
	}

	return Events.Query(append(mods,
		sm.Where(psql.Group(EventColumns.ID).In(PKArgs...)),
	)...)
}

// CCarTeams starts a query for related objects on c_car_team
func (o *CCarEntry) CCarTeams(mods ...bob.Mod[*dialect.SelectQuery]) CCarTeamsQuery {
	return CCarTeams.Query(append(mods,
		sm.Where(CCarTeamColumns.CCarEntryID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CCarEntrySlice) CCarTeams(mods ...bob.Mod[*dialect.SelectQuery]) CCarTeamsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ID)
	}

	return CCarTeams.Query(append(mods,
		sm.Where(psql.Group(CCarTeamColumns.CCarEntryID).In(PKArgs...)),
	)...)
}

func (o *CCarEntry) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CCarDrivers":
		rels, ok := retrieved.(CCarDriverSlice)
		if !ok {
			return fmt.Errorf("cCarEntry cannot load %T as %q", retrieved, name)
		}

		o.R.CCarDrivers = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.CCarEntry = o
			}
		}
		return nil
	case "CCar":
		rel, ok := retrieved.(*CCar)
		if !ok {
			return fmt.Errorf("cCarEntry cannot load %T as %q", retrieved, name)
		}

		o.R.CCar = rel

		if rel != nil {
			rel.R.CCarEntries = CCarEntrySlice{o}
		}
		return nil
	case "Event":
		rel, ok := retrieved.(*Event)
		if !ok {
			return fmt.Errorf("cCarEntry cannot load %T as %q", retrieved, name)
		}

		o.R.Event = rel

		if rel != nil {
			rel.R.CCarEntries = CCarEntrySlice{o}
		}
		return nil
	case "CCarTeams":
		rels, ok := retrieved.(CCarTeamSlice)
		if !ok {
			return fmt.Errorf("cCarEntry cannot load %T as %q", retrieved, name)
		}

		o.R.CCarTeams = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.CCarEntry = o
			}
		}
		return nil
	default:
		return fmt.Errorf("cCarEntry has no relationship %q", name)
	}
}

func ThenLoadCCarEntryCCarDrivers(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadCCarEntryCCarDrivers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load CCarEntryCCarDrivers", retrieved)
		}

		err := loader.LoadCCarEntryCCarDrivers(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadCCarEntryCCarDrivers loads the cCarEntry's CCarDrivers into the .R struct
func (o *CCarEntry) LoadCCarEntryCCarDrivers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CCarDrivers = nil

	related, err := o.CCarDrivers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.CCarEntry = o
	}

	o.R.CCarDrivers = related
	return nil
}

// LoadCCarEntryCCarDrivers loads the cCarEntry's CCarDrivers into the .R struct
func (os CCarEntrySlice) LoadCCarEntryCCarDrivers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	cCarDrivers, err := os.CCarDrivers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.CCarDrivers = nil
	}

	for _, o := range os {
		for _, rel := range cCarDrivers {
			if o.ID != rel.CCarEntryID {
				continue
			}

			rel.R.CCarEntry = o

			o.R.CCarDrivers = append(o.R.CCarDrivers, rel)
		}
	}

	return nil
}

func PreloadCCarEntryCCar(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*CCar, CCarSlice](orm.Relationship{
		Name: "CCar",
		Sides: []orm.RelSide{
			{
				From: TableNames.CCarEntries,
				To:   TableNames.CCars,
				FromColumns: []string{
					ColumnNames.CCarEntries.CCarID,
				},
				ToColumns: []string{
					ColumnNames.CCars.ID,
				},
			},
		},
	}, CCars.Columns().Names(), opts...)
}

func ThenLoadCCarEntryCCar(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadCCarEntryCCar(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load CCarEntryCCar", retrieved)
		}

		err := loader.LoadCCarEntryCCar(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadCCarEntryCCar loads the cCarEntry's CCar into the .R struct
func (o *CCarEntry) LoadCCarEntryCCar(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CCar = nil

	related, err := o.CCar(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CCarEntries = CCarEntrySlice{o}

	o.R.CCar = related
	return nil
}

// LoadCCarEntryCCar loads the cCarEntry's CCar into the .R struct
func (os CCarEntrySlice) LoadCCarEntryCCar(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	cCars, err := os.CCar(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range cCars {
			if o.CCarID != rel.ID {
				continue
			}

			rel.R.CCarEntries = append(rel.R.CCarEntries, o)

			o.R.CCar = rel
			break
		}
	}

	return nil
}

func PreloadCCarEntryEvent(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*Event, EventSlice](orm.Relationship{
		Name: "Event",
		Sides: []orm.RelSide{
			{
				From: TableNames.CCarEntries,
				To:   TableNames.Events,
				FromColumns: []string{
					ColumnNames.CCarEntries.EventID,
				},
				ToColumns: []string{
					ColumnNames.Events.ID,
				},
			},
		},
	}, Events.Columns().Names(), opts...)
}

func ThenLoadCCarEntryEvent(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadCCarEntryEvent(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load CCarEntryEvent", retrieved)
		}

		err := loader.LoadCCarEntryEvent(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadCCarEntryEvent loads the cCarEntry's Event into the .R struct
func (o *CCarEntry) LoadCCarEntryEvent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Event = nil

	related, err := o.Event(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CCarEntries = CCarEntrySlice{o}

	o.R.Event = related
	return nil
}

// LoadCCarEntryEvent loads the cCarEntry's Event into the .R struct
func (os CCarEntrySlice) LoadCCarEntryEvent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	events, err := os.Event(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range events {
			if o.EventID != rel.ID {
				continue
			}

			rel.R.CCarEntries = append(rel.R.CCarEntries, o)

			o.R.Event = rel
			break
		}
	}

	return nil
}

func ThenLoadCCarEntryCCarTeams(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadCCarEntryCCarTeams(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load CCarEntryCCarTeams", retrieved)
		}

		err := loader.LoadCCarEntryCCarTeams(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadCCarEntryCCarTeams loads the cCarEntry's CCarTeams into the .R struct
func (o *CCarEntry) LoadCCarEntryCCarTeams(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CCarTeams = nil

	related, err := o.CCarTeams(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.CCarEntry = o
	}

	o.R.CCarTeams = related
	return nil
}

// LoadCCarEntryCCarTeams loads the cCarEntry's CCarTeams into the .R struct
func (os CCarEntrySlice) LoadCCarEntryCCarTeams(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	cCarTeams, err := os.CCarTeams(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.CCarTeams = nil
	}

	for _, o := range os {
		for _, rel := range cCarTeams {
			if o.ID != rel.CCarEntryID {
				continue
			}

			rel.R.CCarEntry = o

			o.R.CCarTeams = append(o.R.CCarTeams, rel)
		}
	}

	return nil
}

func insertCCarEntryCCarDrivers0(ctx context.Context, exec bob.Executor, cCarDrivers1 []*CCarDriverSetter, cCarEntry0 *CCarEntry) (CCarDriverSlice, error) {
	for i := range cCarDrivers1 {
		cCarDrivers1[i].CCarEntryID = omit.From(cCarEntry0.ID)
	}

	ret, err := CCarDrivers.Insert(bob.ToMods(cCarDrivers1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCCarEntryCCarDrivers0: %w", err)
	}

	return ret, nil
}

func attachCCarEntryCCarDrivers0(ctx context.Context, exec bob.Executor, count int, cCarDrivers1 CCarDriverSlice, cCarEntry0 *CCarEntry) (CCarDriverSlice, error) {
	setter := &CCarDriverSetter{
		CCarEntryID: omit.From(cCarEntry0.ID),
	}

	err := cCarDrivers1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCCarEntryCCarDrivers0: %w", err)
	}

	return cCarDrivers1, nil
}

func (cCarEntry0 *CCarEntry) InsertCCarDrivers(ctx context.Context, exec bob.Executor, related ...*CCarDriverSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	cCarDrivers1, err := insertCCarEntryCCarDrivers0(ctx, exec, related, cCarEntry0)
	if err != nil {
		return err
	}

	cCarEntry0.R.CCarDrivers = append(cCarEntry0.R.CCarDrivers, cCarDrivers1...)

	for _, rel := range cCarDrivers1 {
		rel.R.CCarEntry = cCarEntry0
	}
	return nil
}

func (cCarEntry0 *CCarEntry) AttachCCarDrivers(ctx context.Context, exec bob.Executor, related ...*CCarDriver) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	cCarDrivers1 := CCarDriverSlice(related)

	_, err = attachCCarEntryCCarDrivers0(ctx, exec, len(related), cCarDrivers1, cCarEntry0)
	if err != nil {
		return err
	}

	cCarEntry0.R.CCarDrivers = append(cCarEntry0.R.CCarDrivers, cCarDrivers1...)

	for _, rel := range related {
		rel.R.CCarEntry = cCarEntry0
	}

	return nil
}

func attachCCarEntryCCar0(ctx context.Context, exec bob.Executor, count int, cCarEntry0 *CCarEntry, cCar1 *CCar) (*CCarEntry, error) {
	setter := &CCarEntrySetter{
		CCarID: omit.From(cCar1.ID),
	}

	err := cCarEntry0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCCarEntryCCar0: %w", err)
	}

	return cCarEntry0, nil
}

func (cCarEntry0 *CCarEntry) InsertCCar(ctx context.Context, exec bob.Executor, related *CCarSetter) error {
	cCar1, err := CCars.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCCarEntryCCar0(ctx, exec, 1, cCarEntry0, cCar1)
	if err != nil {
		return err
	}

	cCarEntry0.R.CCar = cCar1

	cCar1.R.CCarEntries = append(cCar1.R.CCarEntries, cCarEntry0)

	return nil
}

func (cCarEntry0 *CCarEntry) AttachCCar(ctx context.Context, exec bob.Executor, cCar1 *CCar) error {
	var err error

	_, err = attachCCarEntryCCar0(ctx, exec, 1, cCarEntry0, cCar1)
	if err != nil {
		return err
	}

	cCarEntry0.R.CCar = cCar1

	cCar1.R.CCarEntries = append(cCar1.R.CCarEntries, cCarEntry0)

	return nil
}

func attachCCarEntryEvent0(ctx context.Context, exec bob.Executor, count int, cCarEntry0 *CCarEntry, event1 *Event) (*CCarEntry, error) {
	setter := &CCarEntrySetter{
		EventID: omit.From(event1.ID),
	}

	err := cCarEntry0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCCarEntryEvent0: %w", err)
	}

	return cCarEntry0, nil
}

func (cCarEntry0 *CCarEntry) InsertEvent(ctx context.Context, exec bob.Executor, related *EventSetter) error {
	event1, err := Events.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCCarEntryEvent0(ctx, exec, 1, cCarEntry0, event1)
	if err != nil {
		return err
	}

	cCarEntry0.R.Event = event1

	event1.R.CCarEntries = append(event1.R.CCarEntries, cCarEntry0)

	return nil
}

func (cCarEntry0 *CCarEntry) AttachEvent(ctx context.Context, exec bob.Executor, event1 *Event) error {
	var err error

	_, err = attachCCarEntryEvent0(ctx, exec, 1, cCarEntry0, event1)
	if err != nil {
		return err
	}

	cCarEntry0.R.Event = event1

	event1.R.CCarEntries = append(event1.R.CCarEntries, cCarEntry0)

	return nil
}

func insertCCarEntryCCarTeams0(ctx context.Context, exec bob.Executor, cCarTeams1 []*CCarTeamSetter, cCarEntry0 *CCarEntry) (CCarTeamSlice, error) {
	for i := range cCarTeams1 {
		cCarTeams1[i].CCarEntryID = omit.From(cCarEntry0.ID)
	}

	ret, err := CCarTeams.Insert(bob.ToMods(cCarTeams1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCCarEntryCCarTeams0: %w", err)
	}

	return ret, nil
}

func attachCCarEntryCCarTeams0(ctx context.Context, exec bob.Executor, count int, cCarTeams1 CCarTeamSlice, cCarEntry0 *CCarEntry) (CCarTeamSlice, error) {
	setter := &CCarTeamSetter{
		CCarEntryID: omit.From(cCarEntry0.ID),
	}

	err := cCarTeams1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCCarEntryCCarTeams0: %w", err)
	}

	return cCarTeams1, nil
}

func (cCarEntry0 *CCarEntry) InsertCCarTeams(ctx context.Context, exec bob.Executor, related ...*CCarTeamSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	cCarTeams1, err := insertCCarEntryCCarTeams0(ctx, exec, related, cCarEntry0)
	if err != nil {
		return err
	}

	cCarEntry0.R.CCarTeams = append(cCarEntry0.R.CCarTeams, cCarTeams1...)

	for _, rel := range cCarTeams1 {
		rel.R.CCarEntry = cCarEntry0
	}
	return nil
}

func (cCarEntry0 *CCarEntry) AttachCCarTeams(ctx context.Context, exec bob.Executor, related ...*CCarTeam) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	cCarTeams1 := CCarTeamSlice(related)

	_, err = attachCCarEntryCCarTeams0(ctx, exec, len(related), cCarTeams1, cCarEntry0)
	if err != nil {
		return err
	}

	cCarEntry0.R.CCarTeams = append(cCarEntry0.R.CCarTeams, cCarTeams1...)

	for _, rel := range related {
		rel.R.CCarEntry = cCarEntry0
	}

	return nil
}
