name: Go Build & Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "./go.mod"

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # don't execute tests in parallel - will collide with reusable testcontainers
      - name: Build & Test
        run: |
          go build -v
          go test ./... -p 1
